import { Inter } from "next/font/google";
import { Karla } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/navbar";
const inter = Inter({ subsets: ["latin"] });
const karla = Karla({subsets:['latin'], variable: '--font-karla'});
const manrope = Manrope({subsets:['latin']});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        <div>{children}</div>
        
      </body>
    </html>
  );
}
